// Mocks generated by Mockito 5.4.6 from annotations
// in supermercado_comparador/test/features/calculadora/presentation/pages/calculadora_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;

import 'package:flutter_bloc/flutter_bloc.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supermercado_comparador/features/calculadora/presentation/bloc/calculadora_bloc.dart'
    as _i14;
import 'package:supermercado_comparador/features/calculadora/presentation/bloc/calculadora_event.dart'
    as _i16;
import 'package:supermercado_comparador/features/calculadora/presentation/bloc/calculadora_state.dart'
    as _i2;
import 'package:supermercado_comparador/features/productos/domain/usecases/create_producto.dart'
    as _i10;
import 'package:supermercado_comparador/features/productos/domain/usecases/delete_producto.dart'
    as _i12;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_all_productos.dart'
    as _i3;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_producto_by_id.dart'
    as _i6;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_producto_by_qr.dart'
    as _i8;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_productos_by_almacen.dart'
    as _i4;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_productos_by_categoria.dart'
    as _i5;
import 'package:supermercado_comparador/features/productos/domain/usecases/search_productos_by_name.dart'
    as _i7;
import 'package:supermercado_comparador/features/productos/domain/usecases/search_productos_with_filters.dart'
    as _i9;
import 'package:supermercado_comparador/features/productos/domain/usecases/update_producto.dart'
    as _i11;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_bloc.dart'
    as _i18;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_event.dart'
    as _i19;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_state.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCalculadoraState_0 extends _i1.SmartFake
    implements _i2.CalculadoraState {
  _FakeCalculadoraState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetAllProductos_1 extends _i1.SmartFake
    implements _i3.GetAllProductos {
  _FakeGetAllProductos_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductosByAlmacen_2 extends _i1.SmartFake
    implements _i4.GetProductosByAlmacen {
  _FakeGetProductosByAlmacen_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductosByCategoria_3 extends _i1.SmartFake
    implements _i5.GetProductosByCategoria {
  _FakeGetProductosByCategoria_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductoById_4 extends _i1.SmartFake
    implements _i6.GetProductoById {
  _FakeGetProductoById_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchProductosByName_5 extends _i1.SmartFake
    implements _i7.SearchProductosByName {
  _FakeSearchProductosByName_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductoByQR_6 extends _i1.SmartFake
    implements _i8.GetProductoByQR {
  _FakeGetProductoByQR_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchProductosWithFilters_7 extends _i1.SmartFake
    implements _i9.SearchProductosWithFilters {
  _FakeSearchProductosWithFilters_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateProducto_8 extends _i1.SmartFake
    implements _i10.CreateProducto {
  _FakeCreateProducto_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateProducto_9 extends _i1.SmartFake
    implements _i11.UpdateProducto {
  _FakeUpdateProducto_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteProducto_10 extends _i1.SmartFake
    implements _i12.DeleteProducto {
  _FakeDeleteProducto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductoState_11 extends _i1.SmartFake
    implements _i13.ProductoState {
  _FakeProductoState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalculadoraBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculadoraBloc extends _i1.Mock implements _i14.CalculadoraBloc {
  MockCalculadoraBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CalculadoraState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeCalculadoraState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.CalculadoraState);

  @override
  _i15.Stream<_i2.CalculadoraState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i15.Stream<_i2.CalculadoraState>.empty(),
      ) as _i15.Stream<_i2.CalculadoraState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i16.CalculadoraEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i16.CalculadoraEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.CalculadoraState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i16.CalculadoraEvent>(
    _i17.EventHandler<E, _i2.CalculadoraState>? handler, {
    _i17.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i17.Transition<_i16.CalculadoraEvent, _i2.CalculadoraState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void onChange(_i17.Change<_i2.CalculadoraState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProductoBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductoBloc extends _i1.Mock implements _i18.ProductoBloc {
  MockProductoBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetAllProductos get getAllProductos => (super.noSuchMethod(
        Invocation.getter(#getAllProductos),
        returnValue: _FakeGetAllProductos_1(
          this,
          Invocation.getter(#getAllProductos),
        ),
      ) as _i3.GetAllProductos);

  @override
  _i4.GetProductosByAlmacen get getProductosByAlmacen => (super.noSuchMethod(
        Invocation.getter(#getProductosByAlmacen),
        returnValue: _FakeGetProductosByAlmacen_2(
          this,
          Invocation.getter(#getProductosByAlmacen),
        ),
      ) as _i4.GetProductosByAlmacen);

  @override
  _i5.GetProductosByCategoria get getProductosByCategoria =>
      (super.noSuchMethod(
        Invocation.getter(#getProductosByCategoria),
        returnValue: _FakeGetProductosByCategoria_3(
          this,
          Invocation.getter(#getProductosByCategoria),
        ),
      ) as _i5.GetProductosByCategoria);

  @override
  _i6.GetProductoById get getProductoById => (super.noSuchMethod(
        Invocation.getter(#getProductoById),
        returnValue: _FakeGetProductoById_4(
          this,
          Invocation.getter(#getProductoById),
        ),
      ) as _i6.GetProductoById);

  @override
  _i7.SearchProductosByName get searchProductosByName => (super.noSuchMethod(
        Invocation.getter(#searchProductosByName),
        returnValue: _FakeSearchProductosByName_5(
          this,
          Invocation.getter(#searchProductosByName),
        ),
      ) as _i7.SearchProductosByName);

  @override
  _i8.GetProductoByQR get getProductoByQR => (super.noSuchMethod(
        Invocation.getter(#getProductoByQR),
        returnValue: _FakeGetProductoByQR_6(
          this,
          Invocation.getter(#getProductoByQR),
        ),
      ) as _i8.GetProductoByQR);

  @override
  _i9.SearchProductosWithFilters get searchProductosWithFilters =>
      (super.noSuchMethod(
        Invocation.getter(#searchProductosWithFilters),
        returnValue: _FakeSearchProductosWithFilters_7(
          this,
          Invocation.getter(#searchProductosWithFilters),
        ),
      ) as _i9.SearchProductosWithFilters);

  @override
  _i10.CreateProducto get createProducto => (super.noSuchMethod(
        Invocation.getter(#createProducto),
        returnValue: _FakeCreateProducto_8(
          this,
          Invocation.getter(#createProducto),
        ),
      ) as _i10.CreateProducto);

  @override
  _i11.UpdateProducto get updateProducto => (super.noSuchMethod(
        Invocation.getter(#updateProducto),
        returnValue: _FakeUpdateProducto_9(
          this,
          Invocation.getter(#updateProducto),
        ),
      ) as _i11.UpdateProducto);

  @override
  _i12.DeleteProducto get deleteProducto => (super.noSuchMethod(
        Invocation.getter(#deleteProducto),
        returnValue: _FakeDeleteProducto_10(
          this,
          Invocation.getter(#deleteProducto),
        ),
      ) as _i12.DeleteProducto);

  @override
  _i13.ProductoState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductoState_11(
          this,
          Invocation.getter(#state),
        ),
      ) as _i13.ProductoState);

  @override
  _i15.Stream<_i13.ProductoState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i15.Stream<_i13.ProductoState>.empty(),
      ) as _i15.Stream<_i13.ProductoState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i19.ProductoEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i19.ProductoEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i13.ProductoState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i19.ProductoEvent>(
    _i17.EventHandler<E, _i13.ProductoState>? handler, {
    _i17.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i17.Transition<_i19.ProductoEvent, _i13.ProductoState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i15.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i15.Future<void>.value(),
        returnValueForMissingStub: _i15.Future<void>.value(),
      ) as _i15.Future<void>);

  @override
  void onChange(_i17.Change<_i13.ProductoState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
