// Mocks generated by Mockito 5.4.6 from annotations
// in supermercado_comparador/test/features/calculadora/data/repositories/calculadora_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supermercado_comparador/features/calculadora/data/datasources/calculadora_local_data_source.dart'
    as _i4;
import 'package:supermercado_comparador/features/calculadora/data/models/item_calculadora_model.dart'
    as _i3;
import 'package:supermercado_comparador/features/calculadora/data/models/lista_compra_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListaCompraModel_0 extends _i1.SmartFake
    implements _i2.ListaCompraModel {
  _FakeListaCompraModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItemCalculadoraModel_1 extends _i1.SmartFake
    implements _i3.ItemCalculadoraModel {
  _FakeItemCalculadoraModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalculadoraLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculadoraLocalDataSource extends _i1.Mock
    implements _i4.CalculadoraLocalDataSource {
  MockCalculadoraLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ListaCompraModel> createListaCompra(
          _i2.ListaCompraModel? listaCompra) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListaCompra,
          [listaCompra],
        ),
        returnValue:
            _i5.Future<_i2.ListaCompraModel>.value(_FakeListaCompraModel_0(
          this,
          Invocation.method(
            #createListaCompra,
            [listaCompra],
          ),
        )),
      ) as _i5.Future<_i2.ListaCompraModel>);

  @override
  _i5.Future<List<_i2.ListaCompraModel>> getAllListasCompra() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllListasCompra,
          [],
        ),
        returnValue: _i5.Future<List<_i2.ListaCompraModel>>.value(
            <_i2.ListaCompraModel>[]),
      ) as _i5.Future<List<_i2.ListaCompraModel>>);

  @override
  _i5.Future<_i2.ListaCompraModel?> getListaCompraById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListaCompraById,
          [id],
        ),
        returnValue: _i5.Future<_i2.ListaCompraModel?>.value(),
      ) as _i5.Future<_i2.ListaCompraModel?>);

  @override
  _i5.Future<_i2.ListaCompraModel> updateListaCompra(
          _i2.ListaCompraModel? listaCompra) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateListaCompra,
          [listaCompra],
        ),
        returnValue:
            _i5.Future<_i2.ListaCompraModel>.value(_FakeListaCompraModel_0(
          this,
          Invocation.method(
            #updateListaCompra,
            [listaCompra],
          ),
        )),
      ) as _i5.Future<_i2.ListaCompraModel>);

  @override
  _i5.Future<void> deleteListaCompra(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteListaCompra,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ItemCalculadoraModel> addItemToLista(
    int? listaId,
    _i3.ItemCalculadoraModel? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemToLista,
          [
            listaId,
            item,
          ],
        ),
        returnValue: _i5.Future<_i3.ItemCalculadoraModel>.value(
            _FakeItemCalculadoraModel_1(
          this,
          Invocation.method(
            #addItemToLista,
            [
              listaId,
              item,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ItemCalculadoraModel>);

  @override
  _i5.Future<_i3.ItemCalculadoraModel> updateItemInLista(
          _i3.ItemCalculadoraModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItemInLista,
          [item],
        ),
        returnValue: _i5.Future<_i3.ItemCalculadoraModel>.value(
            _FakeItemCalculadoraModel_1(
          this,
          Invocation.method(
            #updateItemInLista,
            [item],
          ),
        )),
      ) as _i5.Future<_i3.ItemCalculadoraModel>);

  @override
  _i5.Future<void> removeItemFromLista(int? itemId) => (super.noSuchMethod(
        Invocation.method(
          #removeItemFromLista,
          [itemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ItemCalculadoraModel>> getItemsForLista(int? listaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsForLista,
          [listaId],
        ),
        returnValue: _i5.Future<List<_i3.ItemCalculadoraModel>>.value(
            <_i3.ItemCalculadoraModel>[]),
      ) as _i5.Future<List<_i3.ItemCalculadoraModel>>);
}
