// Mocks generated by Mockito 5.4.6 from annotations
// in supermercado_comparador/test/features/calculadora/presentation/widgets/agregar_producto_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:flutter_bloc/flutter_bloc.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supermercado_comparador/features/productos/domain/usecases/create_producto.dart'
    as _i9;
import 'package:supermercado_comparador/features/productos/domain/usecases/delete_producto.dart'
    as _i11;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_all_productos.dart'
    as _i2;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_producto_by_id.dart'
    as _i5;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_producto_by_qr.dart'
    as _i7;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_productos_by_almacen.dart'
    as _i3;
import 'package:supermercado_comparador/features/productos/domain/usecases/get_productos_by_categoria.dart'
    as _i4;
import 'package:supermercado_comparador/features/productos/domain/usecases/search_productos_by_name.dart'
    as _i6;
import 'package:supermercado_comparador/features/productos/domain/usecases/search_productos_with_filters.dart'
    as _i8;
import 'package:supermercado_comparador/features/productos/domain/usecases/update_producto.dart'
    as _i10;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_bloc.dart'
    as _i13;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_event.dart'
    as _i15;
import 'package:supermercado_comparador/features/productos/presentation/bloc/producto_state.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllProductos_0 extends _i1.SmartFake
    implements _i2.GetAllProductos {
  _FakeGetAllProductos_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductosByAlmacen_1 extends _i1.SmartFake
    implements _i3.GetProductosByAlmacen {
  _FakeGetProductosByAlmacen_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductosByCategoria_2 extends _i1.SmartFake
    implements _i4.GetProductosByCategoria {
  _FakeGetProductosByCategoria_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductoById_3 extends _i1.SmartFake
    implements _i5.GetProductoById {
  _FakeGetProductoById_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchProductosByName_4 extends _i1.SmartFake
    implements _i6.SearchProductosByName {
  _FakeSearchProductosByName_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetProductoByQR_5 extends _i1.SmartFake
    implements _i7.GetProductoByQR {
  _FakeGetProductoByQR_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchProductosWithFilters_6 extends _i1.SmartFake
    implements _i8.SearchProductosWithFilters {
  _FakeSearchProductosWithFilters_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateProducto_7 extends _i1.SmartFake
    implements _i9.CreateProducto {
  _FakeCreateProducto_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateProducto_8 extends _i1.SmartFake
    implements _i10.UpdateProducto {
  _FakeUpdateProducto_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteProducto_9 extends _i1.SmartFake
    implements _i11.DeleteProducto {
  _FakeDeleteProducto_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductoState_10 extends _i1.SmartFake
    implements _i12.ProductoState {
  _FakeProductoState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductoBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductoBloc extends _i1.Mock implements _i13.ProductoBloc {
  MockProductoBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllProductos get getAllProductos => (super.noSuchMethod(
        Invocation.getter(#getAllProductos),
        returnValue: _FakeGetAllProductos_0(
          this,
          Invocation.getter(#getAllProductos),
        ),
      ) as _i2.GetAllProductos);

  @override
  _i3.GetProductosByAlmacen get getProductosByAlmacen => (super.noSuchMethod(
        Invocation.getter(#getProductosByAlmacen),
        returnValue: _FakeGetProductosByAlmacen_1(
          this,
          Invocation.getter(#getProductosByAlmacen),
        ),
      ) as _i3.GetProductosByAlmacen);

  @override
  _i4.GetProductosByCategoria get getProductosByCategoria =>
      (super.noSuchMethod(
        Invocation.getter(#getProductosByCategoria),
        returnValue: _FakeGetProductosByCategoria_2(
          this,
          Invocation.getter(#getProductosByCategoria),
        ),
      ) as _i4.GetProductosByCategoria);

  @override
  _i5.GetProductoById get getProductoById => (super.noSuchMethod(
        Invocation.getter(#getProductoById),
        returnValue: _FakeGetProductoById_3(
          this,
          Invocation.getter(#getProductoById),
        ),
      ) as _i5.GetProductoById);

  @override
  _i6.SearchProductosByName get searchProductosByName => (super.noSuchMethod(
        Invocation.getter(#searchProductosByName),
        returnValue: _FakeSearchProductosByName_4(
          this,
          Invocation.getter(#searchProductosByName),
        ),
      ) as _i6.SearchProductosByName);

  @override
  _i7.GetProductoByQR get getProductoByQR => (super.noSuchMethod(
        Invocation.getter(#getProductoByQR),
        returnValue: _FakeGetProductoByQR_5(
          this,
          Invocation.getter(#getProductoByQR),
        ),
      ) as _i7.GetProductoByQR);

  @override
  _i8.SearchProductosWithFilters get searchProductosWithFilters =>
      (super.noSuchMethod(
        Invocation.getter(#searchProductosWithFilters),
        returnValue: _FakeSearchProductosWithFilters_6(
          this,
          Invocation.getter(#searchProductosWithFilters),
        ),
      ) as _i8.SearchProductosWithFilters);

  @override
  _i9.CreateProducto get createProducto => (super.noSuchMethod(
        Invocation.getter(#createProducto),
        returnValue: _FakeCreateProducto_7(
          this,
          Invocation.getter(#createProducto),
        ),
      ) as _i9.CreateProducto);

  @override
  _i10.UpdateProducto get updateProducto => (super.noSuchMethod(
        Invocation.getter(#updateProducto),
        returnValue: _FakeUpdateProducto_8(
          this,
          Invocation.getter(#updateProducto),
        ),
      ) as _i10.UpdateProducto);

  @override
  _i11.DeleteProducto get deleteProducto => (super.noSuchMethod(
        Invocation.getter(#deleteProducto),
        returnValue: _FakeDeleteProducto_9(
          this,
          Invocation.getter(#deleteProducto),
        ),
      ) as _i11.DeleteProducto);

  @override
  _i12.ProductoState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductoState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i12.ProductoState);

  @override
  _i14.Stream<_i12.ProductoState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i14.Stream<_i12.ProductoState>.empty(),
      ) as _i14.Stream<_i12.ProductoState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i15.ProductoEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i15.ProductoEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i12.ProductoState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i15.ProductoEvent>(
    _i16.EventHandler<E, _i12.ProductoState>? handler, {
    _i16.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i16.Transition<_i15.ProductoEvent, _i12.ProductoState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i14.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i14.Future<void>.value(),
        returnValueForMissingStub: _i14.Future<void>.value(),
      ) as _i14.Future<void>);

  @override
  void onChange(_i16.Change<_i12.ProductoState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
